### ISSUE TITLE
[dev_ansible_v2] IndexError: list index out of range in _strip_sudo

### ISSUE THREAD

**Issue by fdutheil** [austinhyde/ansible-sshjail#12]
Hi,

I'm testing the latest dev_ansible_v2 with either vanilla ansible 2.0.1.0 or your patched version, and I get:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 120, in run
    res = self._execute()
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 418, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/pymodules/python2.7/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/lib/pymodules/python2.7/ansible/plugins/action/__init__.py", line 459, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/lib/pymodules/python2.7/ansible/plugins/action/__init__.py", line 520, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/home/user/Documents/ansible/connection_plugins/sshjail.py", line 104, in exec_command
    cmd = self._strip_sudo(executable, cmd)
  File "/home/user/Documents/ansible/connection_plugins/sshjail.py", line 94, in _strip_sudo
    cmd = cmd.split('; ', 1)[1]
IndexError: list index out of range
```

I inserted a noobish "print(cmd)/print(executable)" into the function to dump call parameters and be able to reproduce it in bpython:

```
>>> cmd = '/bin/sh -c \'sudo -H -S -n -u root /bin/sh -c \'"\'"\'echo BECOME-SUCCESS-fqfhllpqznhajqrrquoecntwwseonzez; /bin/sh -c \'"\'"\'"\'"\'"\'"\'"\'"\'LAN
G=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/local/bin/python /root/.ansible/tmp/ansible-tmp-1458059451.03-12134202492962/ping; rm -rf "/root/
.ansible/tmp/ansible-tmp-1458059451.03-12134202492962/" > /dev/null 2>&1\'"\'"\'"\'"\'"\'"\'"\'"\'\'"\'"\'\''
>>> executable='/bin/sh'
>>> sudoless = cmd.rsplit(executable + ' -c ', 1)[1]
>>> print(sudoless)
'"'"'"'"'"'"'"'"'LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/local/bin/python /root/.ansible/tmp/ansible-tmp-1458059451.03-12134202492962/
ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1458059451.03-12134202492962/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
>>> quotes = sudoless.partition('echo')[0]
>>> print(quotes)
'"'"'"'"'"'"'"'"'LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/local/bin/python /root/.ansible/tmp/ansible-tmp-1458059451.03-12134202492962/
ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1458059451.03-12134202492962/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
>>> cmd = sudoless[len(quotes):-len(quotes+'?')]
>>> print(cmd)

>>> cmd = cmd.split('; ', 1)[1]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
IndexError: list index out of range

```

**Comment by austinhyde** [comment]
Hmm, that's certainly very interesting. I'll look into it when I get some more time. I admit, we have to jump through some pretty hacky hoops to get things to work properly under v2's way of doing things.

Thanks for the detailed investigation!

**Comment by ajette** [comment]
+1

**Comment by fdutheil** [comment]
Hi,
Just a quick update to say that I'm finally able to pick up things where I left them months ago. In the meantime, I now use a vanilla ansible v2.1.1, and the latest sshjail connection pluging from the dev_ansible_v2 branch. And the thing is I'm able to use my WIP playbooks again without any issue now. And I feel like slapping in the face my months old self for not providing a simple test case to reproduce this issue...
Anyway, I guess the june commits I missed where super effective, great job. I'll work a bit more on this in the following weeks and close this issue if I can't reproduce it anymore.

**Comment by BigJ64** [comment]
@fdutheil Thanks for the update.
