### ISSUE TITLE
ImportError: No module named callbacks

### ISSUE THREAD

**Issue by 0utsider** [austinhyde/ansible-sshjail#14]
In my hosts file: 

```
[server]
server.example.com

[jails]
test@server.example.com ansible_python_interpreter=/usr/local/bin/python2.7 ansible_connection=sshjail ansible_ssh_port=2200
```

in playbook: 

```
    - name: hostname in jail
      delegate_to: test@server
      shell: hostname
      tags: jail
```

when I try run like this: 
`ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook go.yml -i hosts -t jail -vvv`

I got error: 

```
TASK [hostname in jail] ********************************************************
task path: /root/ansible/idesign/go.yml:201
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 411, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 636, in _get_connection
    connection = self._shared_loader_obj.connection_loader.get(conn_type, self._play_context, self._new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 333, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 319, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/connection/sshjail.py", line 9, in <module>
    from ansible.callbacks import vvv
ImportError: No module named callbacks

fatal: [server.example.com]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

<server.example.com> ESTABLISH SSH CONNECTION FOR USER: None
<server.example.com> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o Port=2200 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r server.example.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475412043.37-71725684956622 `" && echo ansible-tmp-1475412043.37-71725684956622="` echo $HOME/.ansible/tmp/ansible-tmp-1475412043.37-71725684956622 `" ) && sleep 0'"'"''

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @go.retry
```

I replace my real server name to server.example.com.

**Comment by BigJ64** [comment]
@0utsider I would be curious what Ansible version you are using and which version of the sshjail plugin you are using.

**Comment by 0utsider** [comment]
I tried to use two version of ansible - 2.0.1.0 and 2.1.0.0 and I take sshjail plugin from: https://github.com/austinhyde/ansible-sshjail.git

**Comment by BigJ64** [comment]
If you are running version 2 of ansible you will need to use this brach of the plugin: https://github.com/austinhyde/ansible-sshjail/tree/dev_ansible_v2

**Comment by 0utsider** [comment]
Thx - but one request to you. 
Change description in master because requirement show Ansible 1.9+ (plus it is misleading).
