### ISSUE TITLE
Looks broken with ansible 2.0.0.2

### ISSUE THREAD

**Issue by bushchannelstepper** [austinhyde/ansible-sshjail#9]
I have it in /ansible/connection_plugins/

```
> ansible-playbook -vvvv -l template1@jailhost.dmz site.yml
Using /ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
3 plays in site.yml
 _______________________________
< PLAY [main playbook] >
 -------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ______________
< TASK [setup] >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/ansible/venv/local/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/ansible/venv/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/ansible/venv/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 366, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/ansible/venv/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 582, in _get_connection
    connection = self._shared_loader_obj.connection_loader.get(conn_type, self._play_context, self._new_stdin)
  File "/ansible/venv/local/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 326, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/ansible/venv/local/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 313, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/ansible/connection_plugins/sshjail.py", line 9, in <module>
    from ansible.callbacks import vvv
ImportError: No module named callbacks

fatal: [template1@jailhost.dmz]: FAILED! => {"failed": true, "stdout": ""}
 ______
```

**Comment by austinhyde** [comment]
Hi, this is correct. Ansible changed much of their plugin architecture for 2.0. @BigJ64 and I are fixing this for 2.0 and 2.1 compatibility in PR #7.

If you're only concerned with 2.0 and depend on this plugin for real work, you can pull down the dev_ansible_v2 branch from this repo, and my [ansible plugin-subclass-checks branch](https://github.com/austinhyde/ansible/tree/plugin-subclass-checks), then use that Ansible checkout as any other Ansible source checkout.

If that's not feasible, I have a workaround in mind that I was hoping to not have to resort to, but I can implement it if you really need it.

It's also worth noting that the 2.0 version of the sshjail plugin is NOT backwards compatible with 1.9, so until 1.9 hits end of life, I'll probably continue to keep master tracking Ansible 1.9, and 2.0+ in its own branch.

**Comment by austinhyde** [comment]
Sorry for the late update, just realized I forgot to let you know: I've updated the dev_ansible_v2 branch to work regardless of whether the aforementioned PR is accepted into mainstream Ansible.
